allowBuilds:
  '@scarf/scarf': set this to true or false
  argon2: set this to true or false
  cpu-features: set this to true or false
  esbuild: false
  protobufjs: set this to true or false
  ssh2: set this to true or false
  unrs-resolver: false
